### ISSUE TITLE
[BUG] Funnel metadynamics tutorial fails due to duplicate default force constants

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/biosimspace#216]
As reported [here](https://github.com/michellab/BioSimSpace/issues/428), the funnel metadynamics tutorial is failing with the following exception:

```
Traceback (most recent call last):
  File "/home/lester/Code/openbiosim/biosimspace_tutorials/02_funnel_metad/fun-metaD-work_dir/openmm_script.py", line 111, in <module>
    simulation = Simulation(prm.topology,
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lester/.conda/envs/openbiosim/lib/python3.11/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lester/.conda/envs/openbiosim/lib/python3.11/site-packages/openmm/openmm.py", line 2694, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Two Forces define different default values for the parameter 'k'
```

This is reproducible with OpenMM 8.0 and 8.1. I'm not sure when this first started happening.

**Comment by velocirraptor23** [comment]
Is this still working with other versions of openMM? Thanks for following this.

Cesar

**Comment by lohedges** [comment]
I'm not sure. I've fixed the issue, though. I just need to use a different variable for the force constant in the different forces that we add, i.e. those for the lower walls, distance restraints, etc. I'm not sure why this wasn't a problem before. Perhaps a change in OpenMM 8.0?

**Comment by velocirraptor23** [comment]
Perhaps. I update constantly my software, I will keep an eye on the changes.

Bests,

Cesar

**Comment by velocirraptor23** [comment]
Seems to work now. Thanks!!!
