### ISSUE TITLE
[BUG] rhombic dodecahedron triclinic spaces not working with OpenMM

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/biosimspace#76]
The rhombic dodecahedron box parameters generated by Sire/BioSimSpace are not working with OpenMM. This is true both before and after the rounding fix introduces in OpenBioSim/sire#51. Internally OpenMM uses the same lattice reduction as us (it checks for reduced box dimensions), so I'm surprised this is not working. Other engines are fine with the parameters. Hopefully it's possible to apply a specific fix for this box type.

```python
In [1]: import BioSimSpace as BSS

In [2]: mol = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

In [3]: box, angles = BSS.Box.rhombicDodecahedronHexagon(3*BSS.Units.Length.nanometer)

In [4]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [5]: p = BSS.Protocol.Minimisation(steps=1000)

In [6]: process = BSS.Process.OpenMM(solvated, p)

In [7]: process.start()
Out[7]: BioSimSpace.Process.OpenMM(<BioSimSpace.System: nMolecules=622>, BioSimSpace.Protocol.Minimisation(steps=1000, restraint=None, force_constant=10.0 kcal_per_mol/angstrom**2), exe='/home/lester/.conda/envs/openbiosim/bin/sire_python', name='openmm', platform='CPU', work_dir='/tmp/tmpijqr1ske', seed=None)

In [8]: process.wait()

In [9]: process.isError()
Out[9]: True

In [10]: process.stderr()
/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/tmp/tmpijqr1ske/openmm_script.py", line 34, in <module>
    simulation = Simulation(prmtop.topology,
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/openmm.py", line 10069, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#boxsize

In [11]: box, angles = BSS.Box.rhombicDodecahedronSquare(3*BSS.Units.Length.nanometer)

In [12]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [13]: process = BSS.Process.OpenMM(solvated, p)

In [14]: process.start()
Out[14]: BioSimSpace.Process.OpenMM(<BioSimSpace.System: nMolecules=632>, BioSimSpace.Protocol.Minimisation(steps=1000, restraint=None, force_constant=10.0 kcal_per_mol/angstrom**2), exe='/home/lester/.conda/envs/openbiosim/bin/sire_python', name='openmm', platform='CPU', work_dir='/tmp/tmpmd9xk4t6', seed=None)

In [15]: process.wait()

In [16]: process.isError()
Out[16]: True

In [17]: process.stderr()
Traceback (most recent call last):
  File "/tmp/tmpmd9xk4t6/openmm_script.py", line 16, in <module>
    prmtop = AmberPrmtopFile('openmm.prm7')
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/amberprmtopfile.py", line 156, in __init__
    top.setPeriodicBoxVectors(computePeriodicBoxVectors(*(box[1:4] + box[0:1]*3)))
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/internal/unitcell.py", line 60, in computePeriodicBoxVectors
    cz = math.sqrt(c_length*c_length-cx*cx-cy*cy)
ValueError: math domain error
```

In both cases the box dimensions and angles are stable, and are the same before/after the fix, i.e.:

```python
In [1]: import BioSimSpace as BSS

In [2]: box, angles = BSS.Box.rhombicDodecahedronHexagon(3*BSS.Units.Length.nanometer)

In [3]: mol = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()

In [4]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [5]: solvated.getBox()
Out[5]:
([30.0000 A, 25.9856 A, 30.0000 A],
 [73.7993 degrees, 120.0000 degrees, 88.8975 degrees])

In [6]: box, angles = BSS.Box.rhombicDodecahedronSquare(3*BSS.Units.Length.nanometer)

In [7]: solvated = BSS.Solvent.tip3p(mol, box=box, angles=angles)

In [8]: solvated.getBox()
Out[8]:
([30.0000 A, 30.0000 A, 30.0000 A],
 [120.0000 degrees, 120.0000 degrees, 90.0000 degrees])
```

**Comment by lohedges** [comment]
Transferred this issue since it appears to be unrelated to our `TriclinicBox` parser and can be entirely handled on the BioSimSpace side.

**Comment by lohedges** [comment]
This is now fixed in OpenMM [here](https://github.com/openmm/openmm/pull/4094). You can no pass box vectors to the `AmberPrmtopFile` constructor, i.e. you can load the inpcrd file first, then pass the box vectors on, e.g.:

```python
from openmm import *
from openmm.app import *
from openmm.unit import *

# Load the coordinate files.
inpcrd = AmberInpcrdFile("input.rst7")

# Load the topology file, specifying the box vectors from the inpcrd.
prmtop = AmberPrmtopFile("input.prm7", periodicBoxVectors=inpcrd.boxVectors)

# Initialise the molecular system.
system = prmtop.createSystem(
    nonbondedMethod=PME, nonbondedCutoff=1 * nanometer, constraints=HBonds
)
```

I'll switch over to using this when it's available in a release via conda-forge, i.e. so we can remove the ParmEd workaround.
